server:
  #端口
  port: 6380

spring:
  #服务名
  application:
    name: spring-redis
  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///test
    username: root
    password: root
  redis:
    host: 116.62.142.69
    port: 6379
    database: 0
    timeout: 500s
    password: 123456
    # 连接池配置，2.0中使用jedis或lettuce配置连接池
    jedis:
      pool:
      # 最大活跃数 不限制
        max-active: -1
        max-idle: 500
        max-wait: -1s
        min-idle: 50
